version: '3'
services:
  frontend:
    ports:
      - "3000:3000"
    build: PollBuddy-Server/frontend

  backend:
    ports:
      - "3001:3001"
    build: PollBuddy-Server/backend
  
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    external: false
