version: '3'
services:
  web:
    ports:
      - "3000:3000"
    build: .
  
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    external: false
