version: '3'
services:
  frontend:
    ports:
      - "3000:3000"
    build: PollBuddy-Server/frontend

  backend:
    ports:
      - "3001:3001"
    build: PollBuddy-Server/backend
  
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  grafana:
    build: PollBuddy-Server/reporting/grafana
    image: "grafana/grafana"
    ports:
      - "3002:3000"

  influxdb:
    build: PollBuddy-Server/reporting/influxdb

volumes:
  mongodata:
    external: false

  grafanadata:
    external: false

  influxdata:
    external: false
