version: '3'
services:
  web:
    ports:
      - "5000:5000"
    image: "node"
  
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    external: false
